make_ino <- function(sensorList, interval, project) {
  projname = gsub('[[:punct:]]|\\s+', '', project)
  len = nchar(projname)
  if (substr(projname, len-2, len) == 'ino') projname = substr(projname, 1, len-3)
  
  pins_available = list(D = c(2, 3, 5:13),
                        A = 0:3)
  spi_available  = TRUE
  lib_files      = NULL
  
  header = paste(sep='\n',
                 '/*************************************',
                 'Generated by EZMet',
                 'http://air.utah.edu/s/ezmet/',
                 'Ben Fasoli')
  header_end <- '*************************************/'
  
  colhdr = NULL
  lib    = '#include "SD.h"'
  init   = 'int interval = 1000;'
  
  setup = paste(sep='\n',
                'void setup() {',
                'Serial.begin(9600);',
                'Serial.println("Generated by EZMet");',
                'Serial.println("http://air.utah.edu/s/ezmet/");',
                'Serial.println("Ben Fasoli");\n',
                'Serial.println();',
                'SD.begin(4);')
  setup_end = '}'
  
  loop  = paste(sep='\n',
                'void loop() {',
                'File file = SD.open("raw.dat", FILE_WRITE);',
                'if (file) {')
  loop_end  = paste(sep='\n',
                    'file.println();',
                    'Serial.println();',
                    '} else {',
                    'Serial.println("ERROR: Could not open SD card file.");',
                    '}',
                    'delay(interval);',
                    '}')
  
  # --------------------------------------------------
  for (sensor in sensorList) {
    lib_files = c(lib_files, dir(paste0('sensors/', sensor, '/lib'), full.names=T))
    source(paste0('sensors/', sensor, '/', sensor, '.R'))
    
    pin = switch(about$type,
                 'D' = {
                   out = head(pins_available$D, 1)
                   validate(need(length(pins_available$D) > 0, 'Not enough digital pins.'))
                   pins_available$D = pins_available$D[-1]
                   out
                 },
                 'Dx2' = {
                   out = head(pins_available$D, 2)
                   validate(need(length(pins_available$D) > 1, 'Not enough digital pins.'))
                   pins_available$D = pins_available$D[0:-2]
                   out
                 },
                 'A' = {
                   out = head(pins_available$A, 1)
                   validate(need(length(pins_available$A) > 0, 'Not enough analog pins.'))
                   pins_available$A = pins_available$A[-1]
                   out 
                 },
                 'SPI' = {
                   validate(need(spi_available, 'SPI already in use.'))
                     spi_available=F
                 })
    
    s = new_sensor(pin)
    
    header = paste(header, '', s$header, sep='\n')
    colhdr = paste(colhdr, s$colhdr, sep=', ')
    lib    = paste(lib, s$lib, sep='\n')
    init   = paste(init, s$init, sep='\n')
    setup  = paste(setup, s$setup, sep='\n')
    loop   = paste(loop, s$loop, sep='\n')
  }
  
  # --------------------------------------------------
  make = list(
    ino = paste(sep='\n',
                header,
                '',
                'Column Names:',
                substring(colhdr, 3),
                header_end,
                '',
                '// Libraries',
                lib,
                '',
                '// Constants',
                init,
                '',
                '// Program Setup',
                setup,
                setup_end,
                '',
                '// Program Loop',
                loop,
                loop_end),
    lib_files = lib_files
  )
  
  outdir = paste0('inos/', projname)
  if (!dir.exists(outdir)) system(paste0('mkdir ', outdir))
  system(paste0('cp ', paste(make$lib_files, collapse=' '), ' ', outdir))
  write(make$ino, paste0(outdir, '/', projname, '.ino'))
  
  return(list(name = projname, dirtozip = outdir))
}
