services:
  shiny_server:
    container_name: shiny_server
    build: .
    ports:
      - 3838:3838
    restart: always
    user: 'root'
    volumes:
      - /srv/shiny-server:/srv/shiny-server:ro
      - /data:/data:ro
      - /var/log/shiny-server:/var/log/shiny-server:rw
