---
title: "SMAUG Cluster Utilization"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    theme: simplex
    css: styles.css
---

```{r setup, include=FALSE}
library(DT)
library(flexdashboard)
library(shiny)

is.init <- reactiveVal(F)

db <- reactiveFileReader(10000, session, 'db.rds', function(x) {
  readRDS(x)
})

# Persistent database for utilization and dates
observe({
  users <- c('ben', 'brett', 'chris', 'daniel', 'derek', 'dien', 'henrique', 'john')
  for (i in 1:length(users)) {
    if (db()$date_end[i] >= Sys.Date()) {
      updateDateInput(session, paste0('ds', users[i]), value=db()$date_start[i])
      updateDateInput(session, paste0('de', users[i]), value=db()$date_end[i])
      updateSliderInput(session, paste0('s', users[i]), value=db()$sliders[i])
    }
  }
  is.init(T)
})

observe({
  if (is.init()) {
    date_start = c(input$dsben, input$dsbrett, input$dschris, input$dsdaniel, input$dsderek, input$dsdien, input$dshenrique, input$dsjohn)
    date_end = c(input$deben, input$debrett, input$dechris, input$dedaniel, input$dederek, input$dedien, input$dehenrique, input$dejohn)
    sliders = c(input$sben, input$sbrett, input$schris, input$sdaniel, input$sderek, input$sdien, input$shenrique, input$sjohn)
    df <- data.frame(date_start = date_start, date_end = date_end, sliders = sliders)
    if (nrow(df) > 4) saveRDS(df, 'db.rds')
  }
})
```

Column {data-width=650}
-----------------------------------------------------------------------

### SMAUG SLURM Userss

```{r}
fixedRow(
  column(2, h4('User (a-z)')),
  column(2, h4('Start')),
  column(6, h4('Node utilization')),
  column(2, h4('End'))
)

hr()

fluidRow(
  column(2, h4('Ben')),
  column(2, dateInput('dsben', NULL, value = Sys.Date())),
  column(6, sliderInput('sben', NULL, 0, 14, 0, step = 1, ticks = F, width = '100%')),
  column(2, dateInput('deben', NULL, value = Sys.Date()))
)

fluidRow(
  column(2, h4('Brett')),
  column(2, dateInput('dsbrett', NULL, value = Sys.Date())),
  column(6, sliderInput('sbrett', NULL, 0, 14, 0, step = 1, ticks = F, width = '100%')),
  column(2, dateInput('debrett', NULL, value = Sys.Date()))
)

fluidRow(
  column(2, h4('Chris')),
  column(2, dateInput('dschris', NULL, value = Sys.Date())),
  column(6, sliderInput('schris', NULL, 0, 14, 0, step = 1, ticks = F, width = '100%')),
  column(2, dateInput('dechris', NULL, value = Sys.Date()))
)

fluidRow(
  column(2, h4('Daniel')),
  column(2, dateInput('dsdaniel', NULL, value = Sys.Date())),
  column(6, sliderInput('sdaniel', NULL, 0, 14, 0, step = 1, ticks = F, width = '100%')),
  column(2, dateInput('dedaniel', NULL, value = Sys.Date()))
)

fluidRow(
  column(2, h4('Derek')),
  column(2, dateInput('dsderek', NULL, value = Sys.Date())),
  column(6, sliderInput('sderek', NULL, 0, 14, 0, step = 1, ticks = F, width = '100%')),
  column(2, dateInput('dederek', NULL, value = Sys.Date()))
)

fluidRow(
  column(2, h4('Dien')),
  column(2, dateInput('dsdien', NULL, value = Sys.Date())),
  column(6, sliderInput('sdien', NULL, 0, 14, 0, step = 1, ticks = F, width = '100%')),
  column(2, dateInput('dedien', NULL, value = Sys.Date()))
)

fluidRow(
  column(2, h4('Henrique')),
  column(2, dateInput('dshenrique', NULL, value = Sys.Date())),
  column(6, sliderInput('shenrique', NULL, 0, 14, 0, step = 1, ticks = F, width = '100%')),
  column(2, dateInput('dehenrique', NULL, value = Sys.Date()))
)

fluidRow(
  column(2, h4('John')),
  column(2, dateInput('dsjohn', NULL, value = Sys.Date())),
  column(6, sliderInput('sjohn', NULL, 0, 14, 0, step = 1, ticks = F, width = '100%')),
  column(2, dateInput('dejohn', NULL, value = Sys.Date()))
)
```

### Current Utilization 
```{r}
slurm <- read.table('slurm_util.txt', stringsAsFactors = F, header = T)
slurm$PARTITION <- NULL
NAME <- slurm$NAME
slurm$NAME <- NULL
#slurm <- arrange(slurm, USER)
datatable(slurm, rownames = NAME, autoHideNavigation = T, options = list(paging = F, searching = F))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Total node allocation

```{r}
renderValueBox({
  sliders = c(input$sben, input$sbrett, input$schris, input$sdaniel, input$sderek, input$sdien, input$shenrique, input$sjohn)
  total <- sum(sliders)
  color <- if (total <= 10) { 'success'
  } else if (total > 10 && total <= 14) { 'warning'
  } else 'danger'
  valueBox(total, color = color, icon = 'fa-refresh fa-spin')
})
```

### Unallocated nodes

```{r}
renderValueBox({
  sliders = c(input$sben, input$sbrett, input$schris, input$sdaniel, input$sderek, input$sdien, input$shenrique, input$sjohn)
  total <- sum(sliders)
  avail <- 15 - total
  color <- if (avail < 1) { 'danger'
  } else if (avail >= 1 && avail <= 4) { 'warning'
  } else 'success'
  icon <- if (avail < 1) { 'fa-ban'
  } else if (avail >= 1 && avail <= 4) { 'fa-thumbs-up'
  } else 'fa-thumbs-up'
  valueBox(avail, color = color, icon = icon)
})
```

### Current actual usage

```{r}
renderValueBox({
  total <- nrow(slurm)
  color <- if (total > 12) { 'danger'
  } else if (total >= 8 && total <= 12) { 'warning'
  } else 'success'
  icon <- if (total > 12) { 'fa-ban'
  } else if (total >= 8 && total <= 12) { 'fa-question-circle'
  } else 'fa-thumbs-up'
  valueBox(total, color = color, icon = icon)
})
```

### More noads available

```{r}
renderValueBox({
  dates = c(input$deben, input$debrett, input$dechris, input$dedaniel, input$dederek, input$dedien, input$dehenrique, input$dejohn)
  dates = dates[dates > Sys.Date()]
  if (length(dates) < 1) {
    closestDate <- 'Now'
  } else {
    closestDate <- min(dates)
    nday <- closestDate - Sys.Date()
    closestDate <- format(closestDate, '%m/%d')
  }
  valueBox(closestDate, color = 'info', icon = 'fa-calendar')
})
```
