---
title: "UATAQ TV Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(jsonlite)
library(leaflet)
library(flexdashboard)
library(plotly)
library(shiny)
library(tidyverse)
```

```{r}

# current <- list()

# df <- reactiveFileReader(30000, session, 
#                          rdsfile,
#                          readRDS)

get_data <- function(file) {
  uataq_wbb <- readRDS
  api <- fromJSON(paste0('http://api.mesowest.net/v2/stations/latest?',
                         '&token=cbcb914c5e3a4d14a24e455ac063371f',
                         '&stids=WBB',
                         '&vars=wind_speed,air_temp'))
  met <- list(
    temp = api$STATION$OBSERVATIONS$air_temp_value_1$value %>%
      (function(.) . * 1.8 + 32), # F
    wspd <- api$STATION$OBSERVATIONS$wind_speed_value_1$value %>%
      (function(.) . * 2.23694) # mph
  )
  list(uataq = uataq, met = met)
}

data <- reactiveFileReader(60e3, session,
                           '/var/www/air.utah.edu/_data.rds',
                           get_data)

# Get Mesowest API weather data ----------------------------------------------

```

Row
-----------------------------------------------------------------------

### Chart A

```{r}
observe(
  str(current())
)
```
